image: otrs5ci

stages:
  - test
  - deploy

job_unit_otrs_Znuny4OTRSMarkTicketSeenUnseen:
  stage: test
  script:
    - env
    - pwd
    - /run.sh
    - su -c "git clone https://github.com/OTRS/module-tools.git" -s /bin/bash otrs
    - su -c "module-tools/link.pl . /opt/otrs/" -s /bin/bash otrs
    - su -c "perl /opt/otrs/bin/otrs.Console.pl Znuny4OTRS::AdvancedPackageManager::InstallSOPM /opt/otrs/Znuny4OTRS-MarkTicketSeenUnseenZoom.sopm" -s /bin/bash otrs
    - su -c "perl /opt/otrs/bin/otrs.Console.pl Dev::UnitTest::Run --test Selenium/Agent/Znuny4OTRSMarkTicketSeenUnseenZoom" -s /bin/bash otrs

job_deploy_otrs_Znuny4OTRSMarkTicketSeenUnseen:
  stage: deploy
  script:
    - sh /sync_repo.sh git@github.com:znuny/Znuny4OTRS-MarkTicketSeenUnseen.git